### ISSUE TITLE
Publish on Conan Center

### ISSUE THREAD

**Issue by p4654545** [lamarrr/STX#19]
**Is your feature request related to a problem? Please describe.**
Adding "stx/2.1.3" to "build_requires" in conanyfile.py would be all required to consume this library, if it was published on [Conan Center](https://conan.io/center/).

**Describe the solution you'd like**
Get STX on Conan Center by adding a recipe to [Conan Center Index](https://github.com/conan-io/conan-center-index)

**Describe alternatives you've considered**
We have standardized to using Conan.

**Additional context**

**Comment by melak47** [comment]
I've contributed a recipe to conan-center-index, stx/1.0.1 is now available there.
