### ISSUE TITLE
TRY_OK with rvalue-reference

### ISSUE THREAD

**Issue by melak47** [lamarrr/STX#20]
**Describe the bug**
The documentation of the TRY_OK macro says:
> `result_expr` must be an expression yielding an r-value (reference) of type `Result`

but if you actually try using it with an rvalue reference, something like:
```cpp
auto dummy() -> stx::Result<int, int> {
    stx::Result<int, int> result = Ok(1);
    TRY_OK(x, std::move(result));
    return Ok(std::move(x));
}
```
You get an error regarding `decltype((result_expr))::error_type`. Looks like some `std::remove_reference_t` is needed.
Same applies to Option and TRY_SOME.

**Expected behavior**
The snippet compiles.

**Comment by lamarrr** [comment]
Nice!
Thanks as always. I've merged this.
