### ISSUE TITLE
clang-format

### ISSUE THREAD

**Issue by sarah-ek** [lamarrr/STX#27]
adding a .clang-format config file to the project root would make it a bit easier to contribute, since we wouldn't have to worry about autoformatters modifying code we didn't author

**Comment by lamarrr** [comment]
that'd be awesome, you can send in a PR for that. Unfortunately, as a single contributor, there's a limit to what I can dedicate my time to.
We use the Google clang-format style/

**Comment by kitegi** [comment]
cool! i'll wait until the current PR is resolved before i make another one, so things don't get messy.

**Comment by lamarrr** [comment]
Hi, Our V2 release is underway and I've added a clang-format file on the v2 branch
See: https://github.com/lamarrr/STX/pull/34
