### ISSUE TITLE
STX_INTERNAL_MAKE_REPORT_ warnings with -Wsign-conversion

### ISSUE THREAD

**Issue by nyanpasu64** [lamarrr/STX#36]
**Describe the bug**
When I include STX master in a CMake project where I build my source files with `-Wconversion -Wsign-conversion`, then `STX_INTERNAL_MAKE_REPORT_` raises a sign conversion warning when converting `fmt_buffer_size` to `size_t`.

https://github.com/lamarrr/STX/blob/9f8f97aa34b6c37850bb1e5625372adc9394e75a/include/stx/report.h#L334-L343

**Expected behavior**
The code has two branches, returning a formatting error if `fmt_buffer_size < 0`. So `fmt_buffer_size` is only casted to `size_t` if non-negative. So perhaps insert an explicit cast (do you prefer static_cast over C-style casts?)?

**Additional context**
Is compiling warning-free with `-Wsign-conversion` in-scope?

**Comment by lamarrr** [comment]
seems this has been solved https://github.com/lamarrr/STX/blob/34f497dd26f638df4b38a789f581e016ac85f62e/include/stx/panic/report.h#L53
