### ISSUE TITLE
Provide a usable way to add the library into other projects

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [lamarrr/STX#4]
Hi!

Since now in C++ we have normal dependency manager (Conan), would be fine, if you provide a package for your library and add it to the central conan repository.

You can choose several options:
* Add your package in conan-center repo
* Add your package in bincrafters repo
* Create your own repo and use this repo as a hosting for your library.

Also don't forget to provide installation instructions in README.

Thank you a lot.

**Comment by tonerdo** [comment]
Vcpkg (https://github.com/microsoft/vcpkg) is also worth considering

**Comment by ZaMaZaN4iK** [comment]
I don't recommend Vcpkg only for one reason: it doesn't support even versioning. Maybe there are some fans of Vcpkg, but I cannot recommend it for using.

**Comment by lamarrr** [comment]
> I don't recommend Vcpkg only for one reason: it doesn't support even versioning. Maybe there are some fans of Vcpkg, but I cannot recommend it for using.

Yeah, that's true. But I think cmake is more usable and configurable than VCPKG. I've used VCPKG for a while but it only had very specific versions.
And it's not easily configurable for cross-compilation.

**Comment by jeanga** [comment]
vcpkg works just fine with CMake, it is esentially based on cmake scripts.
And vcpkg has Windows, MacOS & Linux support.

**Comment by lamarrr** [comment]
I've made a port request on the VCPKG repo

**Comment by jeanga** [comment]
I am trying to add vcpkg support for STX.
I have "almost" working Windows port files now (at least on Windows for now).
Unfortunately, building a shared library won't be supported at first because STX does not have the dllspec(dllexport) on the necessary entry points (cf https://docs.microsoft.com/en-us/cpp/build/exporting-from-a-dll-using-declspec-dllexport?view=vs-2019)
I'll keep you updated on my progress here.

**Comment by lamarrr** [comment]
Thanks to @jeanga , this is now available on VCPKG!

**Comment by pseyfert** [comment]
would it maybe make sense to backport (some of) the cmake patches in vcpkg? https://github.com/microsoft/vcpkg/blob/master/ports/stx/CMakeLists.patch (i'm just cloned stx and stumbled over the absence of an install target doing `cmake path/to/source ; cmake --build . --target install`)
